# SPDX-FileCopyrightText: 2021 IDM Südtirol Alto Adige <info@idm-suedtirol.com>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/node.dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run build"
    #command: sh -c "npm install;"
    #command: sh -c "npm run build;"
    #command: sh -c "npm run start:dev"
    ports:
      - "9000:9000"
    tty: true